# Satellite Land Cover Classification

## Notebook 02 — Feature Extraction

In this notebook we:

- Load the EuroSAT satellite images
- Extract handcrafted image features
- Create a structured machine learning dataset
- Save the processed dataset for model training

In [9]:
from pathlib import Path

import pandas as pd
from PIL import Image
from tqdm.auto import tqdm

from landcover.feature_extraction import extract_features

from landcover.dataset import get_feature_names

In [2]:
# ============================================================
# Dataset Paths
# ============================================================

RAW_DATASET = Path("../data/raw/eurosat_subset")

OUTPUT_DATASET = Path("../data/processed")

OUTPUT_DATASET.mkdir(
    parents=True,
    exist_ok=True
)

CSV_FILE = OUTPUT_DATASET / "satellite_landcover_features.csv"

print("Raw Dataset:")
print(RAW_DATASET)

print()

print("Output CSV:")
print(CSV_FILE)

Raw Dataset:
../data/raw/eurosat_subset

Output CSV:
../data/processed/satellite_landcover_features.csv

In [3]:
# ============================================================
# Find Land Cover Classes
# ============================================================

classes = sorted([

    folder.name

    for folder in RAW_DATASET.iterdir()

    if folder.is_dir()

])

print("Classes Found:")

classes

Classes Found:

['Forest', 'Residential', 'River']

In [4]:
# ============================================================
# Extract Features
# ============================================================

rows = []

for landcover_class in classes:

    image_files = sorted(

        (RAW_DATASET / landcover_class).glob("*.jpg")

    )

    print(f"{landcover_class}: {len(image_files)} images")

    for image_path in tqdm(

        image_files,

        desc=landcover_class

    ):

        image = Image.open(image_path).convert("RGB")

        features = extract_features(image)

        features["Label"] = landcover_class

        rows.append(features)

Forest: 3000 images

Forest:   0%|          | 0/3000 [00:00<?, ?it/s]

Residential: 3000 images

Residential:   0%|          | 0/3000 [00:00<?, ?it/s]

River: 2500 images

River:   0%|          | 0/2500 [00:00<?, ?it/s]

In [5]:
# ============================================================
# Build Dataset
# ============================================================

df = pd.DataFrame(rows)

print("Dataset Shape:")

print(df.shape)

print()

display(df.head())

Dataset Shape:
(8500, 8)

,Mean_R,Mean_G,Mean_B,Std_R,Std_G,Std_B,Brightness,Label
0,38.907227,61.089111,77.587158,3.355148,3.718372,2.444745,59.194499,Forest
1,45.481689,66.981934,82.469482,3.508174,3.772286,2.516653,64.977702,Forest
2,45.184570,73.712646,76.645020,6.167868,7.254827,4.319567,65.180745,Forest
3,35.677246,60.892334,72.488525,3.244260,3.449748,2.442176,56.352702,Forest
4,35.402100,58.652832,68.913574,4.031454,4.095310,2.415334,54.322835,Forest

In [6]:
# ============================================================
# Save Dataset
# ============================================================

df.to_csv(

    CSV_FILE,

    index=False

)

print("Dataset saved successfully!")

print(CSV_FILE)

Dataset saved successfully!
../data/processed/satellite_landcover_features.csv

In [7]:
# ============================================================
# Verify Saved Dataset
# ============================================================

verification_df = pd.read_csv(CSV_FILE)

print("Verification Successful!")

print()

print(verification_df.shape)

display(verification_df.head())

Verification Successful!

(8500, 8)

,Mean_R,Mean_G,Mean_B,Std_R,Std_G,Std_B,Brightness,Label
0,38.907227,61.089111,77.587158,3.355148,3.718372,2.444745,59.194499,Forest
1,45.481689,66.981934,82.469482,3.508174,3.772286,2.516653,64.977702,Forest
2,45.184570,73.712646,76.645020,6.167868,7.254827,4.319567,65.180745,Forest
3,35.677246,60.892334,72.488525,3.244260,3.449748,2.442176,56.352702,Forest
4,35.402100,58.652832,68.913574,4.031454,4.095310,2.415334,54.322835,Forest

In [10]:
# ============================================================
# Feature Extraction Summary
# ============================================================

print("=" * 60)
print("FEATURE EXTRACTION COMPLETE")
print("=" * 60)

print(f"Images Processed : {len(df):,}")

print(f"Classes          : {df['Label'].nunique()}")

print(f"Features         : {len(get_feature_names())}")

print()

print("Feature Columns")

for feature in get_feature_names():

    print(f"  • {feature}")

print()

print("Class Distribution")

print(df["Label"].value_counts())

print()

print("Dataset Saved To")

print(CSV_FILE)

print()

print("=" * 60)

============================================================
FEATURE EXTRACTION COMPLETE
============================================================
Images Processed : 8,500
Classes          : 3
Features         : 7

Feature Columns
  • Mean_R
  • Mean_G
  • Mean_B
  • Std_R
  • Std_G
  • Std_B
  • Brightness

Class Distribution
Label
Forest         3000
Residential    3000
River          2500
Name: count, dtype: int64

Dataset Saved To
../data/processed/satellite_landcover_features.csv

============================================================